# Generated by Django 4.1.2 on 2022-10-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_news_preamble'),
    ]

    operations = [
    ]
