# Generated by Django 4.1.2 on 2022-10-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_data_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='update_date',
            new_name='updated',
        ),
    ]
