# Generated by Django 4.1.2 on 2022-10-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_update_date_lesson_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='create_date',
            new_name='created',
        ),
    ]
