# Generated by Django 4.1.2 on 2022-10-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_create_date_lesson_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-create_date',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
